name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Check files using the black formatter
        id: action_black
        uses: rickstaa/action-black@v1
        with:
          black_args: "."
      - name: Create Pull Request
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Format Python code with psf/black push"
          commit-message: ":art: Format Python code with psf/black"
          base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
          branch: actions/black
          reviewers: rxx
          assignees: rxx
          labels: lint
          body: |
            There appear to be some python formatting errors in ${{ github.sha }}. This pull request
            uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.